### PR TITLE
JNA-RInChI

### PR DESCRIPTION
**Pull request by ntk73**
Code is implemented as new maven modules: jna-rinchi-core and binary wrappers modules: jna-rinchi-linux-arm, jna-rinchi-linux-x86,...

### CODE REVIEW

**Comment by uli-f** [comment]
I added an exclude clause to the `license-maven-plugin` of top-level `pom.xml`:
```
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>3.0</version>
    <configuration>
      <header>licenseheader.txt</header>
      <includes>
        <include>**/*.java</include>
      </includes>
      <excludes>
        <exclude>**/jnarinchi/**/*.java</exclude>
      </excludes>
    </configuration>
    <executions>
      <execution>
        <goals>
          <goal>check</goal>
        </goals>
      </execution>
    </executions>
</plugin>
```
This was necessary as the `licenseheader.txt` file that is referred to contains your name as the copyright holder.

**Comment by dan2097** [comment]
Are the three classes that start with __ supposed to be part of this pull request?
 [__DemoApp.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-077675b241f608cce9234fd68fb207cd3cf65d246ef57eaa674068fa11201f8f) [__MiscTest.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-fdf070c77cc52e7c95991c85727d9a032ae328432ad095c9d9d658485bb24e0e)
[__ROSDALParser.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-332b73bc25a160af2d2a78f70f9cf241e4b1bb61520d84fab0691ea64cc9b2b6)

EDIT: it looks like they were added in the recent commit that renames the module

**Comment by ntk73** [comment]
> Are the three classes that start with __ supposed to be part of this pull request? [__DemoApp.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-077675b241f608cce9234fd68fb207cd3cf65d246ef57eaa674068fa11201f8f) [__MiscTest.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-fdf070c77cc52e7c95991c85727d9a032ae328432ad095c9d9d658485bb24e0e) [__ROSDALParser.java](https://github.com/dan2097/jna-inchi/pull/20/files#diff-332b73bc25a160af2d2a78f70f9cf241e4b1bb61520d84fab0691ea64cc9b2b6)
> 

Not at all. These should not be part of the pull request.

> EDIT: it looks like they were added in the recent commit that renames the module

You are right. 
They were added in the recent changes when renaming was done. This is a silly error. These classes were untracked by git files in my local repo. It appears that on module renaming these were added to the git but I did not notice that. You could delete these 3 files.

**Comment by ntk73** [comment]
If you prefer, we could do a new clean pull request or just push another commit to the current pull request which deletes these 3 (what best fits your workflow)

**Comment by ntk73** [comment]
@dan2097 , Dan now after the pull request is merged, I would like to remind you to fix point **1.2 (TBD)**  in file https://github.com/dan2097/jna-inchi/blob/master/RELEASE-NOTES.md

**Comment by dan2097** [comment]
@ntk73  I presume you'd like me to do a release within the next couple of weeks?
BTW I added jna-rinchi-core as a dependency of the jna-inchi-all module so the behaviour is consistent with that described in the readme.

**Comment by ntk73** [comment]
> @ntk73 I presume you'd like me to do a release within the next couple of weeks? 

Generally, ASAP works best for us :-) since we will use jna-rinchi dependency for cdk-rinchi module finalization. But I do not know what time schedule you have discussed with @uli-f. So let him comment on this. 

>BTW I added jna-rinchi-core as a dependency of the jna-inchi-all module so the behaviour is consistent with that described in the readme.

OK

**Comment by uli-f** [comment]
@dan2097 Thank you for merging 😃 

> > @ntk73 I presume you'd like me to do a release within the next couple of weeks?
> 
> Generally, ASAP works best for us :-)

Yes please, anytime works for us.

> > BTW I added jna-rinchi-core as a dependency of the jna-inchi-all module so the behaviour is consistent with that described in the readme.
> 
> OK

Thanks, that makes sense.

**Comment by dan2097** [comment]
This is now released.

Just to double check, was I correct in changing the description of the jna-rinchi-linux-arm module to RInChI **32-bit** ARM Linux support e.g. Raspberry Pi. My understanding is that the Raspberry Pi OS, at least until very recently, is typically 32-bit. My description of the jna-inchi-linux-arm also contained this mistake.

**Comment by ntk73** [comment]
> This is now released.
> 
Great. Thanks

> Just to double check, was I correct in changing the description of the jna-rinchi-linux-arm module to RInChI **32-bit** ARM Linux support e.g. Raspberry Pi. My understanding is that the Raspberry Pi OS, at least until very recently, is typically 32-bit. My description of the jna-inchi-linux-arm also contained this mistake.

Yes, your change in commit a8cea265ecbff06c3ff1c08b62b67b27dca43a67 is correct. 
I did a copy-paste from inchi modules, so this error was present in jna-rinchi as well.

**Pull request merged**
